// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ManagementAPI.IntegrationTests.Reporting
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "base")]
    [Xunit.TraitAttribute("Category", "golfclub")]
    [Xunit.TraitAttribute("Category", "player")]
    [Xunit.TraitAttribute("Category", "tournament")]
    [Xunit.TraitAttribute("Category", "reporting")]
    [Xunit.TraitAttribute("Category", "golfclubadministrator")]
    public partial class PlayerReportsFeature : Xunit.IClassFixture<PlayerReportsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PlayerReports.feature"
#line hidden
        
        public PlayerReportsFeature(PlayerReportsFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "PlayerReports", null, ProgrammingLanguage.CSharp, new string[] {
                        "base",
                        "golfclub",
                        "player",
                        "tournament",
                        "reporting",
                        "golfclubadministrator"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line hidden
            TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                        "GolfClubNumber",
                        "EmailAddress",
                        "GivenName",
                        "MiddleName",
                        "FamilyName",
                        "Password",
                        "ConfirmPassword",
                        "TelephoneNumber"});
            table36.AddRow(new string[] {
                        "1",
                        "admin@testgolfclub1.co.uk",
                        "Admin",
                        "",
                        "User1",
                        "123456",
                        "123456",
                        "01234567890"});
#line 5
 testRunner.Given("the following golf club administrator has been registered", ((string)(null)), table36, "Given ");
#line 8
 testRunner.And("I am logged in as the administrator for golf club 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                        "GolfClubNumber",
                        "GolfClubName",
                        "AddressLine1",
                        "AddressLine2",
                        "Town",
                        "Region",
                        "PostalCode",
                        "TelephoneNumber",
                        "EmailAddress",
                        "WebSite"});
            table37.AddRow(new string[] {
                        "1",
                        "Test Golf Club 1",
                        "Test Golf Club Address Line 1",
                        "Test Golf Club Address Line",
                        "TestTown1",
                        "TestRegion",
                        "TE57 1NG",
                        "01234567890",
                        "testclub1@testclub1.co.uk",
                        "www.testclub1.co.uk"});
#line 9
 testRunner.When("I create a golf club with the following details", ((string)(null)), table37, "When ");
#line 12
 testRunner.Then("the golf club is created successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                        "GolfClubNumber",
                        "MeasuredCourseNumber",
                        "Name",
                        "StandardScratchScore",
                        "TeeColour"});
            table38.AddRow(new string[] {
                        "1",
                        "1",
                        "Test Course",
                        "70",
                        "White"});
#line 13
 testRunner.When("I add a measured course to the club with the following details", ((string)(null)), table38, "When ");
#line hidden
            TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                        "GolfClubNumber",
                        "MeasuredCourseNumber",
                        "HoleNumber",
                        "LengthInYards",
                        "Par",
                        "StrokeIndex"});
            table39.AddRow(new string[] {
                        "1",
                        "1",
                        "1",
                        "348",
                        "4",
                        "10"});
            table39.AddRow(new string[] {
                        "1",
                        "1",
                        "2",
                        "402",
                        "4",
                        "4"});
            table39.AddRow(new string[] {
                        "1",
                        "1",
                        "3",
                        "207",
                        "3",
                        "14"});
            table39.AddRow(new string[] {
                        "1",
                        "1",
                        "4",
                        "405",
                        "4",
                        "8"});
            table39.AddRow(new string[] {
                        "1",
                        "1",
                        "5",
                        "428",
                        "4",
                        "2"});
            table39.AddRow(new string[] {
                        "1",
                        "1",
                        "6",
                        "477",
                        "5",
                        "12"});
            table39.AddRow(new string[] {
                        "1",
                        "1",
                        "7",
                        "186",
                        "3",
                        "16"});
            table39.AddRow(new string[] {
                        "1",
                        "1",
                        "8",
                        "397",
                        "4",
                        "6"});
            table39.AddRow(new string[] {
                        "1",
                        "1",
                        "9",
                        "130",
                        "3",
                        "18"});
            table39.AddRow(new string[] {
                        "1",
                        "1",
                        "10",
                        "399",
                        "4",
                        "3"});
            table39.AddRow(new string[] {
                        "1",
                        "1",
                        "11",
                        "401",
                        "4",
                        "13"});
            table39.AddRow(new string[] {
                        "1",
                        "1",
                        "12",
                        "421",
                        "4",
                        "1"});
            table39.AddRow(new string[] {
                        "1",
                        "1",
                        "13",
                        "530",
                        "5",
                        "11"});
            table39.AddRow(new string[] {
                        "1",
                        "1",
                        "14",
                        "196",
                        "3",
                        "5"});
            table39.AddRow(new string[] {
                        "1",
                        "1",
                        "15",
                        "355",
                        "4",
                        "7"});
            table39.AddRow(new string[] {
                        "1",
                        "1",
                        "16",
                        "243",
                        "4",
                        "15"});
            table39.AddRow(new string[] {
                        "1",
                        "1",
                        "17",
                        "286",
                        "4",
                        "17"});
            table39.AddRow(new string[] {
                        "1",
                        "1",
                        "18",
                        "399",
                        "4",
                        "9"});
#line 16
 testRunner.And("with the following holes", ((string)(null)), table39, "And ");
#line 36
 testRunner.Then("the measured course is added to the club successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                        "TournamentNumber",
                        "TournamentName",
                        "TournamentMonth",
                        "TournamentDay",
                        "TournamentFormat",
                        "PlayerCategory",
                        "MeasuredCourseName",
                        "GolfClubNumber"});
            table40.AddRow(new string[] {
                        "1",
                        "Test Tournament 1",
                        "April",
                        "5",
                        "Strokeplay",
                        "Gents",
                        "Test Course",
                        "1"});
            table40.AddRow(new string[] {
                        "2",
                        "Test Tournament 2",
                        "May",
                        "5",
                        "Strokeplay",
                        "Gents",
                        "Test Course",
                        "1"});
            table40.AddRow(new string[] {
                        "3",
                        "Test Tournament 3",
                        "May",
                        "10",
                        "Strokeplay",
                        "Gents",
                        "Test Course",
                        "1"});
            table40.AddRow(new string[] {
                        "4",
                        "Test Tournament 4",
                        "June",
                        "15",
                        "Strokeplay",
                        "Gents",
                        "Test Course",
                        "1"});
            table40.AddRow(new string[] {
                        "5",
                        "Test Tournament 5",
                        "July",
                        "12",
                        "Strokeplay",
                        "Gents",
                        "Test Course",
                        "1"});
            table40.AddRow(new string[] {
                        "6",
                        "Test Tournament 6",
                        "July",
                        "19",
                        "Strokeplay",
                        "Gents",
                        "Test Course",
                        "1"});
            table40.AddRow(new string[] {
                        "7",
                        "Test Tournament 7",
                        "August",
                        "25",
                        "Strokeplay",
                        "Gents",
                        "Test Course",
                        "1"});
            table40.AddRow(new string[] {
                        "8",
                        "Test Tournament 8",
                        "September",
                        "1",
                        "Strokeplay",
                        "Gents",
                        "Test Course",
                        "1"});
#line 37
 testRunner.Given("When I create a tournament with the following details", ((string)(null)), table40, "Given ");
#line 47
 testRunner.Then("tournament number 1 for golf club 1 measured course \'Test Course\' will be created" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 48
 testRunner.And("tournament number 2 for golf club 1 measured course \'Test Course\' will be created" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
 testRunner.And("tournament number 3 for golf club 1 measured course \'Test Course\' will be created" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 50
 testRunner.And("tournament number 4 for golf club 1 measured course \'Test Course\' will be created" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
 testRunner.And("tournament number 5 for golf club 1 measured course \'Test Course\' will be created" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 52
 testRunner.And("tournament number 6 for golf club 1 measured course \'Test Course\' will be created" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 53
 testRunner.And("tournament number 7 for golf club 1 measured course \'Test Course\' will be created" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 54
 testRunner.And("tournament number 8 for golf club 1 measured course \'Test Course\' will be created" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                        "PlayerNumber",
                        "EmailAddress",
                        "GivenName",
                        "MiddleName",
                        "FamilyName",
                        "Age",
                        "Gender",
                        "ExactHandicap"});
            table41.AddRow(new string[] {
                        "1",
                        "testplayer1@players.co.uk",
                        "Test",
                        "",
                        "Player1",
                        "25",
                        "M",
                        "6.2"});
#line 56
 testRunner.Given("the following players have registered", ((string)(null)), table41, "Given ");
#line 60
 testRunner.Given("I am logged in as player number 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 62
 testRunner.When("I request membership of club number 1 for player number 1 the request is successf" +
                    "ul", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 64
 testRunner.When("player number 1 signs up to play in tournament number 1 for golf club 1 measured " +
                    "course \'Test Course\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 65
 testRunner.Then("player number 1 is recorded as signed up for tournament number 1 for golf club 1 " +
                    "measured course \'Test Course\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 67
 testRunner.When("player number 1 signs up to play in tournament number 2 for golf club 1 measured " +
                    "course \'Test Course\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 68
 testRunner.Then("player number 1 is recorded as signed up for tournament number 2 for golf club 1 " +
                    "measured course \'Test Course\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 70
 testRunner.When("player number 1 signs up to play in tournament number 3 for golf club 1 measured " +
                    "course \'Test Course\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 71
 testRunner.Then("player number 1 is recorded as signed up for tournament number 3 for golf club 1 " +
                    "measured course \'Test Course\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 73
 testRunner.When("player number 1 signs up to play in tournament number 4 for golf club 1 measured " +
                    "course \'Test Course\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 74
 testRunner.Then("player number 1 is recorded as signed up for tournament number 4 for golf club 1 " +
                    "measured course \'Test Course\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 76
 testRunner.When("player number 1 signs up to play in tournament number 5 for golf club 1 measured " +
                    "course \'Test Course\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 77
 testRunner.Then("player number 1 is recorded as signed up for tournament number 5 for golf club 1 " +
                    "measured course \'Test Course\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 79
 testRunner.When("player number 1 signs up to play in tournament number 6 for golf club 1 measured " +
                    "course \'Test Course\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 80
 testRunner.Then("player number 1 is recorded as signed up for tournament number 6 for golf club 1 " +
                    "measured course \'Test Course\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 82
 testRunner.When("player number 1 signs up to play in tournament number 7 for golf club 1 measured " +
                    "course \'Test Course\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 83
 testRunner.Then("player number 1 is recorded as signed up for tournament number 7 for golf club 1 " +
                    "measured course \'Test Course\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 85
 testRunner.When("player number 1 signs up to play in tournament number 8 for golf club 1 measured " +
                    "course \'Test Course\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 86
 testRunner.Then("player number 1 is recorded as signed up for tournament number 8 for golf club 1 " +
                    "measured course \'Test Course\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                        "PlayerNumber",
                        "Hole1",
                        "Hole2",
                        "Hole3",
                        "Hole4",
                        "Hole5",
                        "Hole6",
                        "Hole7",
                        "Hole8",
                        "Hole9",
                        "Hole10",
                        "Hole11",
                        "Hole12",
                        "Hole13",
                        "Hole14",
                        "Hole15",
                        "Hole16",
                        "Hole17",
                        "Hole18"});
            table42.AddRow(new string[] {
                        "1",
                        "4",
                        "5",
                        "4",
                        "4",
                        "4",
                        "5",
                        "3",
                        "4",
                        "3",
                        "4",
                        "4",
                        "4",
                        "5",
                        "3",
                        "4",
                        "4",
                        "4",
                        "4"});
#line 88
 testRunner.When("a player records the following score for tournament number 1 for golf club 1 meas" +
                    "ured course \'Test Course\'", ((string)(null)), table42, "When ");
#line 91
 testRunner.Then("the scores recorded by the players are recorded against tournament number 1 for g" +
                    "olf club 1 measured course \'Test Course\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 92
 testRunner.When("I request to complete the tournament number 1 for golf club 1 measured course \'Te" +
                    "st Course\' the tournament is completed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 93
 testRunner.When("I request to produce a tournament result for tournament number 1 for golf club 1 " +
                    "measured course \'Test Course\' the results are produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                        "PlayerNumber",
                        "Hole1",
                        "Hole2",
                        "Hole3",
                        "Hole4",
                        "Hole5",
                        "Hole6",
                        "Hole7",
                        "Hole8",
                        "Hole9",
                        "Hole10",
                        "Hole11",
                        "Hole12",
                        "Hole13",
                        "Hole14",
                        "Hole15",
                        "Hole16",
                        "Hole17",
                        "Hole18"});
            table43.AddRow(new string[] {
                        "1",
                        "4",
                        "5",
                        "4",
                        "4",
                        "4",
                        "5",
                        "3",
                        "4",
                        "3",
                        "4",
                        "4",
                        "4",
                        "5",
                        "3",
                        "4",
                        "4",
                        "4",
                        "4"});
#line 95
 testRunner.When("a player records the following score for tournament number 2 for golf club 1 meas" +
                    "ured course \'Test Course\'", ((string)(null)), table43, "When ");
#line 98
 testRunner.Then("the scores recorded by the players are recorded against tournament number 2 for g" +
                    "olf club 1 measured course \'Test Course\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 99
 testRunner.When("I request to complete the tournament number 2 for golf club 1 measured course \'Te" +
                    "st Course\' the tournament is completed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 100
 testRunner.When("I request to produce a tournament result for tournament number 2 for golf club 1 " +
                    "measured course \'Test Course\' the results are produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table44 = new TechTalk.SpecFlow.Table(new string[] {
                        "PlayerNumber",
                        "Hole1",
                        "Hole2",
                        "Hole3",
                        "Hole4",
                        "Hole5",
                        "Hole6",
                        "Hole7",
                        "Hole8",
                        "Hole9",
                        "Hole10",
                        "Hole11",
                        "Hole12",
                        "Hole13",
                        "Hole14",
                        "Hole15",
                        "Hole16",
                        "Hole17",
                        "Hole18"});
            table44.AddRow(new string[] {
                        "1",
                        "4",
                        "5",
                        "4",
                        "4",
                        "4",
                        "5",
                        "3",
                        "4",
                        "3",
                        "4",
                        "4",
                        "4",
                        "5",
                        "3",
                        "4",
                        "4",
                        "4",
                        "4"});
#line 102
 testRunner.When("a player records the following score for tournament number 3 for golf club 1 meas" +
                    "ured course \'Test Course\'", ((string)(null)), table44, "When ");
#line 105
 testRunner.Then("the scores recorded by the players are recorded against tournament number 3 for g" +
                    "olf club 1 measured course \'Test Course\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 106
 testRunner.When("I request to complete the tournament number 3 for golf club 1 measured course \'Te" +
                    "st Course\' the tournament is completed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 107
 testRunner.When("I request to produce a tournament result for tournament number 3 for golf club 1 " +
                    "measured course \'Test Course\' the results are produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table45 = new TechTalk.SpecFlow.Table(new string[] {
                        "PlayerNumber",
                        "Hole1",
                        "Hole2",
                        "Hole3",
                        "Hole4",
                        "Hole5",
                        "Hole6",
                        "Hole7",
                        "Hole8",
                        "Hole9",
                        "Hole10",
                        "Hole11",
                        "Hole12",
                        "Hole13",
                        "Hole14",
                        "Hole15",
                        "Hole16",
                        "Hole17",
                        "Hole18"});
            table45.AddRow(new string[] {
                        "1",
                        "4",
                        "5",
                        "4",
                        "4",
                        "4",
                        "5",
                        "3",
                        "4",
                        "3",
                        "4",
                        "4",
                        "4",
                        "5",
                        "3",
                        "4",
                        "4",
                        "4",
                        "4"});
#line 109
 testRunner.When("a player records the following score for tournament number 4 for golf club 1 meas" +
                    "ured course \'Test Course\'", ((string)(null)), table45, "When ");
#line 112
 testRunner.Then("the scores recorded by the players are recorded against tournament number 4 for g" +
                    "olf club 1 measured course \'Test Course\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 113
 testRunner.When("I request to complete the tournament number 4 for golf club 1 measured course \'Te" +
                    "st Course\' the tournament is completed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 114
 testRunner.When("I request to produce a tournament result for tournament number 4 for golf club 1 " +
                    "measured course \'Test Course\' the results are produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table46 = new TechTalk.SpecFlow.Table(new string[] {
                        "PlayerNumber",
                        "Hole1",
                        "Hole2",
                        "Hole3",
                        "Hole4",
                        "Hole5",
                        "Hole6",
                        "Hole7",
                        "Hole8",
                        "Hole9",
                        "Hole10",
                        "Hole11",
                        "Hole12",
                        "Hole13",
                        "Hole14",
                        "Hole15",
                        "Hole16",
                        "Hole17",
                        "Hole18"});
            table46.AddRow(new string[] {
                        "1",
                        "4",
                        "5",
                        "4",
                        "4",
                        "4",
                        "5",
                        "3",
                        "4",
                        "3",
                        "4",
                        "4",
                        "4",
                        "5",
                        "3",
                        "4",
                        "4",
                        "4",
                        "4"});
#line 116
 testRunner.When("a player records the following score for tournament number 5 for golf club 1 meas" +
                    "ured course \'Test Course\'", ((string)(null)), table46, "When ");
#line 119
 testRunner.Then("the scores recorded by the players are recorded against tournament number 5 for g" +
                    "olf club 1 measured course \'Test Course\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 120
 testRunner.When("I request to complete the tournament number 5 for golf club 1 measured course \'Te" +
                    "st Course\' the tournament is completed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 121
 testRunner.When("I request to produce a tournament result for tournament number 5 for golf club 1 " +
                    "measured course \'Test Course\' the results are produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table47 = new TechTalk.SpecFlow.Table(new string[] {
                        "PlayerNumber",
                        "Hole1",
                        "Hole2",
                        "Hole3",
                        "Hole4",
                        "Hole5",
                        "Hole6",
                        "Hole7",
                        "Hole8",
                        "Hole9",
                        "Hole10",
                        "Hole11",
                        "Hole12",
                        "Hole13",
                        "Hole14",
                        "Hole15",
                        "Hole16",
                        "Hole17",
                        "Hole18"});
            table47.AddRow(new string[] {
                        "1",
                        "4",
                        "5",
                        "4",
                        "4",
                        "4",
                        "5",
                        "3",
                        "4",
                        "3",
                        "4",
                        "4",
                        "4",
                        "5",
                        "3",
                        "4",
                        "4",
                        "4",
                        "4"});
#line 123
 testRunner.When("a player records the following score for tournament number 6 for golf club 1 meas" +
                    "ured course \'Test Course\'", ((string)(null)), table47, "When ");
#line 126
 testRunner.Then("the scores recorded by the players are recorded against tournament number 6 for g" +
                    "olf club 1 measured course \'Test Course\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 127
 testRunner.When("I request to complete the tournament number 6 for golf club 1 measured course \'Te" +
                    "st Course\' the tournament is completed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 128
 testRunner.When("I request to produce a tournament result for tournament number 6 for golf club 1 " +
                    "measured course \'Test Course\' the results are produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table48 = new TechTalk.SpecFlow.Table(new string[] {
                        "PlayerNumber",
                        "Hole1",
                        "Hole2",
                        "Hole3",
                        "Hole4",
                        "Hole5",
                        "Hole6",
                        "Hole7",
                        "Hole8",
                        "Hole9",
                        "Hole10",
                        "Hole11",
                        "Hole12",
                        "Hole13",
                        "Hole14",
                        "Hole15",
                        "Hole16",
                        "Hole17",
                        "Hole18"});
            table48.AddRow(new string[] {
                        "1",
                        "4",
                        "5",
                        "4",
                        "4",
                        "4",
                        "5",
                        "3",
                        "4",
                        "3",
                        "4",
                        "4",
                        "4",
                        "5",
                        "3",
                        "4",
                        "4",
                        "4",
                        "4"});
#line 130
 testRunner.When("a player records the following score for tournament number 7 for golf club 1 meas" +
                    "ured course \'Test Course\'", ((string)(null)), table48, "When ");
#line 133
 testRunner.Then("the scores recorded by the players are recorded against tournament number 7 for g" +
                    "olf club 1 measured course \'Test Course\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 134
 testRunner.When("I request to complete the tournament number 7 for golf club 1 measured course \'Te" +
                    "st Course\' the tournament is completed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 135
 testRunner.When("I request to produce a tournament result for tournament number 7 for golf club 1 " +
                    "measured course \'Test Course\' the results are produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table49 = new TechTalk.SpecFlow.Table(new string[] {
                        "PlayerNumber",
                        "Hole1",
                        "Hole2",
                        "Hole3",
                        "Hole4",
                        "Hole5",
                        "Hole6",
                        "Hole7",
                        "Hole8",
                        "Hole9",
                        "Hole10",
                        "Hole11",
                        "Hole12",
                        "Hole13",
                        "Hole14",
                        "Hole15",
                        "Hole16",
                        "Hole17",
                        "Hole18"});
            table49.AddRow(new string[] {
                        "1",
                        "4",
                        "5",
                        "4",
                        "4",
                        "4",
                        "5",
                        "3",
                        "4",
                        "3",
                        "4",
                        "4",
                        "4",
                        "5",
                        "3",
                        "4",
                        "4",
                        "4",
                        "4"});
#line 137
 testRunner.When("a player records the following score for tournament number 8 for golf club 1 meas" +
                    "ured course \'Test Course\'", ((string)(null)), table49, "When ");
#line 140
 testRunner.Then("the scores recorded by the players are recorded against tournament number 8 for g" +
                    "olf club 1 measured course \'Test Course\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 141
 testRunner.When("I request to complete the tournament number 8 for golf club 1 measured course \'Te" +
                    "st Course\' the tournament is completed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 142
 testRunner.When("I request to produce a tournament result for tournament number 8 for golf club 1 " +
                    "measured course \'Test Course\' the results are produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Player Scores Report")]
        [Xunit.TraitAttribute("FeatureTitle", "PlayerReports")]
        [Xunit.TraitAttribute("Description", "Player Scores Report")]
        public virtual void PlayerScoresReport()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player Scores Report", null, ((string[])(null)));
#line 144
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 4
this.FeatureBackground();
#line 146
 testRunner.When("I request a number of scores report for player number 1 with the last 5 scores", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 147
 testRunner.Then("I am returned the number of scores report data successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 148
 testRunner.And("the number of scores count for player number 1 is 5", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table50 = new TechTalk.SpecFlow.Table(new string[] {
                        "TournamentName",
                        "TournamentMonth",
                        "TournamentDay"});
            table50.AddRow(new string[] {
                        "Test Tournament 4",
                        "June",
                        "15"});
            table50.AddRow(new string[] {
                        "Test Tournament 5",
                        "July",
                        "12"});
            table50.AddRow(new string[] {
                        "Test Tournament 6",
                        "July",
                        "19"});
            table50.AddRow(new string[] {
                        "Test Tournament 7",
                        "August",
                        "25"});
            table50.AddRow(new string[] {
                        "Test Tournament 8",
                        "September",
                        "1"});
#line 149
 testRunner.And("the following scores are returned for player 1", ((string)(null)), table50, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                PlayerReportsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                PlayerReportsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
