// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MobileAppConfigurationAPI.Database;

namespace MobileAppConfigurationAPI.Migrations
{
    [DbContext(typeof(MobileConfiguration))]
    [Migration("20190226222649_InitialDatabase")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MobileAppConfigurationAPI.Database.Models.ApplicationConfiguration", b =>
                {
                    b.Property<string>("IMEINumber")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ManagementApiUri");

                    b.Property<string>("SecurityServiceUri");

                    b.HasKey("IMEINumber");

                    b.ToTable("ApplicationConfiguration");
                });
#pragma warning restore 612, 618
        }
    }
}
