name: ASP.NET Core CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: restore packages
      run: dotnet restore API/ManagementAPI/ManagementAPI.sln
    
    - name: rebuild code
      run: dotnet build --configuration Release API/ManagementAPI/ManagementAPI.sln

    - name: run unit tests
      run: dotnet test API/ManagementAPI/ManagementAPI.Service.Tests/ManagementAPI.Service.Tests.csproj
    
    - name: run integration tests
      run: dotnet test API/ManagementAPI/ManagementAPI.Service.IntegrationTests/ManagementAPI.Service.IntegrationTests.csproj

    - name: buld docker image
      run: docker docker build -t managementapi:latest --pull -f Dockerfile ../
    
    - name: run specflow tests
      run: dotnet test API/ManagementAPI/ManagementAPI.IntegrationTests/ManagementAPI.IntegrationTests.csproj --filter Category=EndToEnd
